import Header from './components/Header'
import './globals.css'
import { Mulish } from 'next/font/google'

const mulish = Mulish({
  subsets: ['latin'],
  dispay: 'swap',
  weight: '400'
})

export const metadata = {
  title: 'Movie Flix',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
